const sgMail = require('@sendgrid/mail');

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

async function sendWillEmail({ to, willId, jurisdiction, pdfBuffer }) {
  try {
    if (!process.env.SENDGRID_API_KEY) {
      throw new Error('SENDGRID_API_KEY is not configured');
    }

    if (!process.env.SENDGRID_FROM_EMAIL) {
      throw new Error('SENDGRID_FROM_EMAIL is not configured');
    }

    const attachments = [];
    if (pdfBuffer) {
      attachments.push({
        content: pdfBuffer.toString('base64'),
        filename: `will_${jurisdiction}_${new Date().toISOString().split('T')[0]}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment'
      });
    }

    const msg = {
      to,
      from: process.env.SENDGRID_FROM_EMAIL,
      subject: 'Your Draft Will from Legal Will Generation Tool (Educational Prototype)',
      text: `
Dear User,

Your draft will document is attached to this email.

IMPORTANT LEGAL DISCLAIMER:
This document was generated by an educational prototype tool and does NOT constitute legal advice.
This is a term project for academic purposes only.

This draft will should be reviewed by a qualified legal professional in your jurisdiction before use.
DO NOT rely on this document for actual legal purposes without professional legal review.

The Legal Will Generation Tool is provided for educational demonstration purposes only.

For legal advice regarding wills and estate planning, please consult a licensed attorney in your jurisdiction.

Best regards,
Legal Will Generation Tool Team
University of Calgary - ENTI333

---
Document ID: ${willId}
Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
`,
      html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background-color: #1E3A8A; color: white; padding: 20px; text-align: center; }
    .content { padding: 20px; background-color: #f9f9f9; }
    .warning { background-color: #FEF3C7; border-left: 4px solid #F59E0B; padding: 15px; margin: 20px 0; }
    .footer { padding: 20px; text-align: center; font-size: 12px; color: #666; }
    .disclaimer { background-color: #FEE2E2; border: 2px solid #EF4444; padding: 15px; margin: 20px 0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Your Draft Will Document</h1>
    </div>
    
    <div class="content">
      <p>Dear User,</p>
      
      <p>Your draft will document is attached to this email.</p>
      
      <div class="disclaimer">
        <h2 style="color: #EF4444; margin-top: 0;">⚠️ IMPORTANT LEGAL DISCLAIMER</h2>
        <p><strong>This document was generated by an educational prototype tool and does NOT constitute legal advice.</strong></p>
        <p>This is a term project for academic purposes only.</p>
        <ul>
          <li>This draft will should be <strong>reviewed by a qualified legal professional</strong> in your jurisdiction before use.</li>
          <li><strong>DO NOT rely on this document</strong> for actual legal purposes without professional legal review.</li>
          <li>The Legal Will Generation Tool is provided for <strong>educational demonstration purposes only</strong>.</li>
        </ul>
      </div>
      
      <div class="warning">
        <p><strong>Next Steps:</strong></p>
        <p>For legal advice regarding wills and estate planning, please consult a licensed attorney in your jurisdiction (${jurisdiction}).</p>
      </div>
      
      <p>Best regards,<br>
      <strong>Legal Will Generation Tool Team</strong><br>
      University of Calgary - ENTI333</p>
    </div>
    
    <div class="footer">
      <p>Document ID: ${willId}<br>
      Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      <p style="margin-top: 20px; font-size: 10px;">
        This is an automated email from an educational project. Please do not reply to this email.
      </p>
    </div>
  </div>
</body>
</html>
`,
      attachments
    };

    const result = await sgMail.send(msg);
    console.log('Email sent successfully:', result[0].statusCode);
    
    return { 
      sent: true, 
      messageId: result[0].headers['x-message-id'] 
    };
  } catch (error) {
    console.error('Error sending email:', error);
    if (error.response) {
      console.error('SendGrid error details:', error.response.body);
    }
    throw error;
  }
}

module.exports = {
  sendWillEmail
};
