const sgMail = require('@sendgrid/mail');

let connectionSettings;

async function getCredentials() {
  const hostname = process.env.REPLIT_CONNECTORS_HOSTNAME;
  const xReplitToken = process.env.REPL_IDENTITY 
    ? 'repl ' + process.env.REPL_IDENTITY 
    : process.env.WEB_REPL_RENEWAL 
    ? 'depl ' + process.env.WEB_REPL_RENEWAL 
    : null;

  console.log('[SendGrid] Fetching credentials from connector...');
  console.log('[SendGrid] Hostname:', hostname);
  console.log('[SendGrid] Token present:', !!xReplitToken);

  if (!xReplitToken) {
    throw new Error('X_REPLIT_TOKEN not found for repl/depl');
  }

  const response = await fetch(
    'https://' + hostname + '/api/v2/connection?include_secrets=true&connector_names=sendgrid',
    {
      headers: {
        'Accept': 'application/json',
        'X_REPLIT_TOKEN': xReplitToken
      }
    }
  );
  
  const data = await response.json();
  console.log('[SendGrid] Connector response:', JSON.stringify(data, null, 2));
  
  connectionSettings = data.items?.[0];

  if (!connectionSettings || (!connectionSettings.settings?.api_key || !connectionSettings.settings?.from_email)) {
    console.error('[SendGrid] Connection settings:', connectionSettings);
    throw new Error('SendGrid not connected or missing credentials');
  }
  
  console.log('[SendGrid] API key starts with:', connectionSettings.settings.api_key?.substring(0, 3));
  console.log('[SendGrid] From email:', connectionSettings.settings.from_email);
  
  return {
    apiKey: connectionSettings.settings.api_key, 
    email: connectionSettings.settings.from_email
  };
}

async function getUncachableSendGridClient() {
  const {apiKey, email} = await getCredentials();
  sgMail.setApiKey(apiKey);
  return {
    client: sgMail,
    fromEmail: email
  };
}

async function sendWillDocumentsEmail(recipientEmail, userName, willPDFBuffer, assessmentPDFBuffer) {
  try {
    const {client, fromEmail} = await getUncachableSendGridClient();
    
    const msg = {
      to: recipientEmail,
      from: fromEmail,
      subject: 'Your Legal Will Documents',
      text: `Dear ${userName},\n\nPlease find attached your legal will documents generated by our AI-assisted legal will tool.\n\nIMPORTANT LEGAL NOTICE:\nThese documents were generated for academic and informational purposes. This tool does not provide legal advice. You MUST consult with a licensed attorney in your jurisdiction before executing this will to ensure it meets all legal requirements.\n\nAttachments:\n1. Last Will and Testament (will.pdf)\n2. Legal Assessment Document (assessment.pdf)\n\nPlease store these documents securely and keep them confidential.\n\nBest regards,\nLegal Will Generation Tool`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h2 style="color: #1E3A8A;">Your Legal Will Documents</h2>
          
          <p>Dear ${userName},</p>
          
          <p>Please find attached your legal will documents generated by our AI-assisted legal will tool.</p>
          
          <div style="background-color: #FEE2E2; border-left: 4px solid #EF4444; padding: 15px; margin: 20px 0;">
            <h3 style="color: #991B1B; margin-top: 0;">IMPORTANT LEGAL NOTICE</h3>
            <p style="color: #991B1B; margin-bottom: 0;">
              These documents were generated for academic and informational purposes. This tool does not provide legal advice. 
              You <strong>MUST</strong> consult with a licensed attorney in your jurisdiction before executing this will to ensure it meets all legal requirements.
            </p>
          </div>
          
          <h3 style="color: #1E3A8A;">Attachments:</h3>
          <ul>
            <li><strong>Last Will and Testament</strong> (will.pdf)</li>
            <li><strong>Legal Assessment Document</strong> (assessment.pdf)</li>
          </ul>
          
          <p style="color: #64748B; font-size: 14px; margin-top: 30px;">
            Please store these documents securely and keep them confidential.
          </p>
          
          <p style="margin-top: 30px;">
            Best regards,<br>
            <strong>Legal Will Generation Tool</strong>
          </p>
        </div>
      `,
      attachments: [
        {
          content: willPDFBuffer.toString('base64'),
          filename: 'will.pdf',
          type: 'application/pdf',
          disposition: 'attachment'
        },
        {
          content: assessmentPDFBuffer.toString('base64'),
          filename: 'assessment.pdf',
          type: 'application/pdf',
          disposition: 'attachment'
        }
      ]
    };

    await client.send(msg);
    console.log('[Email Service] Successfully sent will documents to:', recipientEmail);
    return { success: true };
    
  } catch (error) {
    console.error('[Email Service] Error sending email:', error);
    throw error;
  }
}

module.exports = {
  sendWillDocumentsEmail
};
